version: '3'

services:
    nginx:
        container_name: sf-nginx-prod
        build:
            context: .
            dockerfile: ./docker/nginx/Dockerfile-nginx_prod
        ports:
            - 80:80
        networks:
            - symfony

    php:
        container_name: sf-php-prod
        build:
            context: .
            dockerfile: ./docker/php/Dockerfile-php_prod
        environment:
            APP_ENV: prod
            DATABASE_URL: mysql://root:secret@mysql:3306/symfony
        expose:
            - 9000
        networks:
            - symfony          
networks:
    symfony:

